### ISSUE TITLE
Please can you add the Wemos D1 Mini to supported boards

### ISSUE THREAD

**Issue by lesp** [vgkits/vgkits-vanguard#8]
As discussed on twitter re: Wemos D1 Mini Support
Here is the information that you requested from the output of

`esptool.py --port /dev/ttyUSB0 flash_id`

`Detecting chip type... ESP8266`
`Chip is ESP8266EX`
`Manufacturer: 20`
`Device: 4016`
`Detected flash size: 4MB`

Cheers
Les

**Comment by cefn** [comment]
Should be resolved by https://github.com/vgkits/vgkits-vanguard/releases/tag/0.2.0_rc12 now available in PyPI
